In [5]:
import numpy as np
ar1 = np.random.randint(40,size =(4,3))
ar1

array([[11,  4, 32],
       [18, 21, 37],
       [19, 25, 14],
       [ 1, 23, 19]])

In [9]:
ar2 = np.random.randint(5,size = (3,))
ar2

array([2, 3, 0])

In [10]:
ar1 + ar2 #ONE OF THE RULES STATES THAT THE COLOUMN SHOULD MATCH WITH THE VECTOR OF THE SECOND ARRAY 

array([[13,  7, 32],
       [20, 24, 37],
       [21, 28, 14],
       [ 3, 26, 19]])

In [11]:
ar3 = np.random.randint(20, size = (4,3))
ar3

array([[ 4, 13, 12],
       [18, 15, 10],
       [ 2, 19, 13],
       [17,  0,  2]])

In [12]:
ar4 = np.random.randint(4, size = (4,1))
ar4

array([[2],
       [3],
       [0],
       [0]])

In [13]:
ar1 + ar2   #IN THIS SECOND RULE WE HAVE TO CHECK IF THE ROW SHOULD BE SIMILAR TO THE SIZE OF THE SECOND VECTOR AND THE SECOD MATRIX SHOULD BE ALWYAS 1

array([[13,  7, 32],
       [20, 24, 37],
       [21, 28, 14],
       [ 3, 26, 19]])