In [1]:
import numpy as np

In [2]:
ar1 = np.array([21,23,443,554])
ar1.shape

(4,)

In [3]:
ar1.ndim

1

In [4]:
ar1.dtype


dtype('int64')

In [5]:
ar2 = np.array([[2,3,6,5],[3,5,4,65],[5,65,4,3]])
ar2.shape

(3, 4)

In [6]:
ar2.ndim

2

In [7]:
ar3 = np.array([[[2,1,2],[2,3,4],[2,3,4]], [[23,33,3],[3,2,4],[2,4,5]], [[3,2,4], [3,4,6],[3,4,6]]])
ar3.ndim

3

In [16]:
ar2.shape

(3, 4)

In [9]:
ar4 = np.array([[[3, 5, 101], [210, 105, 10]], [[10, 15, 105], [110, 100, 1]], [[13, 51, 11], [200, 55, 41]], [[-1, -5, -10], [218, 81, 8]]])
ar4.shape

(4, 2, 3)

In [10]:
ar4.ndim

3

In [11]:
lis1 = [12,34,43,23,12,332,1223,4343]
[el+10 for el in lis1]

[22, 44, 53, 33, 22, 342, 1233, 4353]

In [12]:
ar1 + 10 #this is called vectorization

array([ 31,  33, 453, 564])

In [13]:
ar4 > 5

array([[[False, False,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True, False]],

       [[ True,  True,  True],
        [ True,  True,  True]],

       [[False, False, False],
        [ True,  True,  True]]])

In [15]:
ar2 * 3

array([[  6,   9,  18,  15],
       [  9,  15,  12, 195],
       [ 15, 195,  12,   9]])

In [21]:
np5 = np.arange(10,14)
np5

array([10, 11, 12, 13])

In [22]:
ar1 + np5

array([ 31,  34, 455, 567])

In [23]:
ar1[2]

np.int64(443)

In [24]:
ar4[1][0:3]

array([[ 10,  15, 105],
       [110, 100,   1]])