boolean indexing

In [14]:
import numpy as np

In [15]:
ar1 = np.array(random.choices(range(10,25), k =24)).reshape((4,6))
ar1

array([[21, 14, 12, 13, 16, 11],
       [23, 23, 11, 16, 13, 15],
       [11, 22, 14, 11, 14, 13],
       [11, 11, 10, 22, 19, 22]])

In [40]:
ar2 = np.array(random.choices(range(10,30), k =24)).reshape((4,6))
values =[True, False, True, False,]
ar2[values]

array([[13, 27, 18, 26, 11, 27],
       [25, 27, 17, 17, 13, 19]])

In [27]:
ar3 = np.array([2,1,32,3,2,1,32,321,342,543])
values =[True, False, True, False,True, False, True, False,True, False]
ar3[values]

array([  2,  32,   2,  32, 342])

In [42]:
ar4 = np.array(random.choices(range(12,70), k = 81)).reshape(9,9)
values =[True, False, True, False,True, False, True, False,False]
ar4[values]

array([[39, 64, 68, 30, 48, 59, 50, 14, 12],
       [46, 62, 36, 38, 66, 37, 42, 31, 62],
       [52, 39, 18, 41, 51, 12, 28, 16, 48],
       [30, 36, 28, 67, 31, 59, 62, 23, 27]])

In [51]:
names = np.array(['bob', 'joe', 'will', 'boboo', 'will', 'joe', 'joe'])
names[names == 'joe']

array(['joe', 'joe', 'joe'], dtype='<U5')

In [52]:
names[names == 'joe'] = 'kathin'
names

array(['bob', 'kathi', 'will', 'boboo', 'will', 'kathi', 'kathi'],
      dtype='<U5')

In [49]:
names = np.array(['bob', 'joe', 'will', 'boboo', 'will', 'joe', 'joe'])
names[(names == 'joe')| (names == 'will')]

array(['joe', 'will', 'will', 'joe', 'joe'], dtype='<U5')

In [50]:
#fancy indexing


In [62]:
ar5 = np.array([[21,23,12], [12,13,13], [13,45,2], [34,21,34], [24,19,18], [16,43,67]])
ar5[[5,4,0,1]]

array([[16, 43, 67],
       [24, 19, 18],
       [21, 23, 12],
       [12, 13, 13]])

In [66]:
ar6 = np.array(random.choices(range(10,30),k= 10)).reshape(2,5)       #transpose of an array
ar6

array([[16, 19, 23, 17, 21],
       [27, 17, 27, 16, 29]])

In [65]:
ar7 = np.array(random.choices(range(10,30),k= 10)).reshape(2,5)