In [7]:
import numpy as np
rng = np.random.default_rng(seed=79)                          #SEED: SAME ARRAY WE WILL GET EVEN THOUGH WE USE RANDOM.
arr1 = rng.standard_normal((3,6))
arr1

array([[ 0.62056346, -0.73341459,  0.41001804, -0.53019673,  1.29739073,
         0.00737916],
       [-1.81719352,  0.55061294, -0.60074953,  0.67644021,  0.56039394,
        -0.47042988],
       [ 0.70939859,  0.01181479,  0.79963258,  0.24876133, -1.82632428,
         0.00934281]])

In [8]:
rng = np.random.default_rng(seed=79)
arr1 = rng.standard_normal((3,6))
arr1

array([[ 0.62056346, -0.73341459,  0.41001804, -0.53019673,  1.29739073,
         0.00737916],
       [-1.81719352,  0.55061294, -0.60074953,  0.67644021,  0.56039394,
        -0.47042988],
       [ 0.70939859,  0.01181479,  0.79963258,  0.24876133, -1.82632428,
         0.00934281]])

In [25]:
import random
ar2 = np.array(random.choices(range(1,50), k = 24)).reshape(4,6)
ar2

array([[21, 15, 24, 29, 31,  4],
       [29, 13, 18,  2,  3, 48],
       [19, 11, 26, 12, 20,  1],
       [34, 43, 18,  2, 13, 27]])

In [26]:
np.square(ar2)

array([[ 441,  225,  576,  841,  961,   16],
       [ 841,  169,  324,    4,    9, 2304],
       [ 361,  121,  676,  144,  400,    1],
       [1156, 1849,  324,    4,  169,  729]])

In [27]:
np.sqrt(ar2)

array([[4.58257569, 3.87298335, 4.89897949, 5.38516481, 5.56776436,
        2.        ],
       [5.38516481, 3.60555128, 4.24264069, 1.41421356, 1.73205081,
        6.92820323],
       [4.35889894, 3.31662479, 5.09901951, 3.46410162, 4.47213595,
        1.        ],
       [5.83095189, 6.55743852, 4.24264069, 1.41421356, 3.60555128,
        5.19615242]])

In [28]:
ar3 = np.array(random.choices(range(20,50),k= 24)).reshape(4,6)
ar3

array([[43, 31, 37, 21, 49, 22],
       [24, 48, 49, 21, 26, 21],
       [45, 26, 46, 23, 48, 36],
       [40, 21, 32, 34, 36, 31]])

In [29]:
np.add(ar2,ar3)

array([[64, 46, 61, 50, 80, 26],
       [53, 61, 67, 23, 29, 69],
       [64, 37, 72, 35, 68, 37],
       [74, 64, 50, 36, 49, 58]])

In [32]:
ar4 = np.array(random.choices(range(20,30), k = 20)).reshape(5,4)
values = [True, False,True,True, False]
ar4[values]

array([[20, 25, 26, 25],
       [24, 24, 22, 28],
       [29, 21, 20, 22]])

In [41]:
ar5 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
values  = [True, False,True,True]
ar5[values]

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [52]:
ar6 = np.random.randint(50,size=(5,9))
ar6

array([[40, 10, 15,  4, 21,  9, 11, 35,  8],
       [37, 25, 16, 20,  6,  5, 42, 34,  4],
       [ 1, 11, 32, 18, 30,  0,  6, 44, 13],
       [20, 39, 14, 15, 16, 47, 11, 49,  8],
       [20, 23, 21, 28, 20, 49,  6, 37, 36]])

In [53]:
ar6.sort(axis = 0)   #WE CAN SEE THAT ITS BEING SORTED AS IN ROWS IT MEANS --------------------->(THIS DIRECTION FOR EVERY ROW)
ar6

array([[ 1, 10, 14,  4,  6,  0,  6, 34,  4],
       [20, 11, 15, 15, 16,  5,  6, 35,  8],
       [20, 23, 16, 18, 20,  9, 11, 37,  8],
       [37, 25, 21, 20, 21, 47, 11, 44, 13],
       [40, 39, 32, 28, 30, 49, 42, 49, 36]])

In [54]:
ar6.sort(axis = 1) #WE CAN SEE THAT ITS BEING SORTED AS IN CLOUMS
ar6

array([[ 0,  1,  4,  4,  6,  6, 10, 14, 34],
       [ 5,  6,  8, 11, 15, 15, 16, 20, 35],
       [ 8,  9, 11, 16, 18, 20, 20, 23, 37],
       [11, 13, 20, 21, 21, 25, 37, 44, 47],
       [28, 30, 32, 36, 39, 40, 42, 49, 49]])

In [59]:
#SET THEORY
ar7 = np.random.randint(40, size = (4,5))
ar8 = np.random.randint(30, size = (4,5))
ar7

array([[27, 18, 15, 19,  0],
       [ 4,  2, 10, 27,  4],
       [29,  6, 39, 27, 33],
       [38, 19, 10, 33,  3]])

In [60]:
ar8

array([[ 2, 13, 20, 18, 28],
       [ 6, 24, 28, 20,  0],
       [16,  8, 19,  3,  1],
       [15, 10, 23, 24,  4]])

In [70]:
np.intersect1d(ar7,ar8,assume_unique = False, return_indices = True)

(array([ 0,  2,  3,  4,  6, 10, 15, 18, 19]),
 array([ 4,  6, 19,  5, 11,  7,  2,  1,  3]),
 array([ 9,  0, 13, 19,  5, 16, 15,  3, 12]))

In [71]:
np.isin(ar7,ar8)

array([[False,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [False,  True, False, False, False],
       [False,  True,  True, False,  True]])

In [77]:
ar9 = np.arange(30)
ar9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [78]:
ar9.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [79]:
ar9.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [83]:
np.concatenate([ar7,ar8], axis = 1)

array([[27, 18, 15, 19,  0,  2, 13, 20, 18, 28],
       [ 4,  2, 10, 27,  4,  6, 24, 28, 20,  0],
       [29,  6, 39, 27, 33, 16,  8, 19,  3,  1],
       [38, 19, 10, 33,  3, 15, 10, 23, 24,  4]])